### ISSUE TITLE
VARNISH_DEFAULT_TTL=600s: not a number

### ISSUE THREAD

**Issue by ccjeagle** [wodby/wordpress-varnish#1]
When setting default ttl, the docker logs will show:
/docker-entrypoint.sh: running /docker-entrypoint-init.d/wordpress-varnish.sh
Error:
Not a number(600s)

(attempting to set param 'default_ttl' to '600s')
(attempting to set param 'thread_pools' to '1')

My docker command:
docker run -d \
          --name test-varnish \
          -e VARNISH_BACKEND_PORT=80 \
          -e VARNISH_BACKEND_HOST=wordpress \
          -e VARNISH_DEFAULT_TTL=600s \
          wodby/wordpress-varnish

I also tried 600. Then the logs will be different:
/docker-entrypoint.sh: running /docker-entrypoint-init.d/wordpress-varnish.sh
Error:
Message from VCC-compiler:
Expected ID got ';'
(program line 166), at
('/etc/varnish/default.vcl' Line 104 Pos 29)
        set beresp.ttl = 600;
----------------------------#

Running VCC-compiler failed, exited with 2
VCL compilation failed

Any advice would be much appreciated. Thanks!

**Comment by ccjeagle** [comment]
wodby/varnish use VARNISH_DEFAULT_TTL in varnishd command which does not take time unit ('s' in this case), whereas in wodby/wordpress-varnish, the VARNISH_DEFAULT_TTL will be in vcl files which would need time unit. The conflict happens then.

**Comment by pprishchepa** [comment]
Could you try to use time without time unit (seconds by default)? Does it work for you?

**Comment by pprishchepa** [comment]
@ccjeagle I've got what you mean. Yes, this is a bug, we'll rename daemon params as `VARNISHD_...`, so it won't intersect with vcl params.

**Comment by pprishchepa** [comment]
The issue has been fixed, you should use `VARNISHD_DEFAULT_TTL` for daemon and `VARNISH_DEFAULT_TTL` for VCL config.
